import type { GCodeParameters } from '../../hooks/useGCodeGeneration';

export async function generateLineScanGCode(
  imageData: ImageData,
  params: GCodeParameters
): Promise<string> {
  const { width, height, data } = imageData;
  const { laserPower, speed, resolution } = params;

  // Calculate scaling factor based on resolution (DPI)
  const pixelsPerMM = resolution / 25.4; // Convert DPI to pixels per mm
  const mmPerPixel = 1 / pixelsPerMM;

  const lines: string[] = [];

  // Header
  lines.push('; Generated by Laser Engraver Studio');
  lines.push('; Line Scan Method');
  lines.push(`; Image size: ${width}x${height} pixels`);
  lines.push(`; Resolution: ${resolution} DPI`);
  lines.push(`; Laser power: ${laserPower}%`);
  lines.push(`; Speed: ${speed} mm/min`);
  lines.push('');

  // Initialize
  lines.push('G21 ; Set units to millimeters');
  lines.push('G90 ; Absolute positioning');
  lines.push('G0 F' + speed); // Set feed rate
  lines.push('M5 ; Laser off');
  lines.push('G0 X0 Y0 ; Move to origin');
  lines.push('');

  // Process image line by line
  for (let y = 0; y < height; y++) {
    let inBurn = false;
    let lastX = 0;

    for (let x = 0; x < width; x++) {
      const idx = (y * width + x) * 4;
      const r = data[idx];
      const g = data[idx + 1];
      const b = data[idx + 2];

      // Convert to grayscale
      const gray = 0.299 * r + 0.587 * g + 0.114 * b;
      const intensity = 255 - gray; // Invert so dark areas burn

      // Calculate laser power for this pixel
      const pixelPower = Math.round((intensity / 255) * laserPower);

      const xPos = (x * mmPerPixel).toFixed(3);
      const yPos = (y * mmPerPixel).toFixed(3);

      if (pixelPower > 5) {
        // Threshold to avoid very light burns
        if (!inBurn) {
          // Start burning
          lines.push(`G0 X${xPos} Y${yPos}`);
          lines.push(`M3 S${pixelPower}`);
          inBurn = true;
        } else if (Math.abs(x - lastX) > 1) {
          // Update position and power
          lines.push(`G1 X${xPos} Y${yPos} S${pixelPower}`);
        }
        lastX = x;
      } else {
        if (inBurn) {
          // Stop burning
          lines.push('M5');
          inBurn = false;
        }
      }
    }

    // End of line
    if (inBurn) {
      lines.push('M5');
    }
  }

  // Footer
  lines.push('');
  lines.push('M5 ; Laser off');
  lines.push('G0 X0 Y0 ; Return to origin');
  lines.push('M2 ; End program');

  return lines.join('\n');
}
