import type { GCodeParameters } from '../../hooks/useGCodeGeneration';

interface Point {
  x: number;
  y: number;
}

interface Contour {
  points: Point[];
}

export async function generateVectorTraceGCode(
  imageData: ImageData,
  params: GCodeParameters
): Promise<string> {
  const { width, height, data } = imageData;
  const { laserPower, speed, resolution } = params;

  // Calculate scaling factor based on resolution (DPI)
  const pixelsPerMM = resolution / 25.4;
  const mmPerPixel = 1 / pixelsPerMM;

  const lines: string[] = [];

  // Header
  lines.push('; Generated by Laser Engraver Studio');
  lines.push('; Vector Trace Method');
  lines.push(`; Image size: ${width}x${height} pixels`);
  lines.push(`; Resolution: ${resolution} DPI`);
  lines.push(`; Laser power: ${laserPower}%`);
  lines.push(`; Speed: ${speed} mm/min`);
  lines.push('');

  // Initialize
  lines.push('G21 ; Set units to millimeters');
  lines.push('G90 ; Absolute positioning');
  lines.push('G0 F' + speed);
  lines.push('M5 ; Laser off');
  lines.push('G0 X0 Y0 ; Move to origin');
  lines.push('');

  // Convert to grayscale and apply threshold
  const threshold = 128;
  const binary = new Uint8Array(width * height);

  for (let i = 0; i < width * height; i++) {
    const idx = i * 4;
    const r = data[idx];
    const g = data[idx + 1];
    const b = data[idx + 2];
    const gray = 0.299 * r + 0.587 * g + 0.114 * b;
    binary[i] = gray < threshold ? 1 : 0;
  }

  // Simple edge detection using Sobel-like approach
  const edges: Point[] = [];

  for (let y = 1; y < height - 1; y++) {
    for (let x = 1; x < width - 1; x++) {
      const idx = y * width + x;

      // Check if this is an edge pixel (has different neighbors)
      const current = binary[idx];
      const hasEdge =
        binary[idx - 1] !== current ||
        binary[idx + 1] !== current ||
        binary[idx - width] !== current ||
        binary[idx + width] !== current;

      if (hasEdge && current === 1) {
        edges.push({ x, y });
      }
    }
  }

  // Group nearby edge points into contours (simplified)
  const contours: Contour[] = [];
  const visited = new Set<string>();

  for (const point of edges) {
    const key = `${point.x},${point.y}`;
    if (visited.has(key)) continue;

    const contour: Contour = { points: [] };
    const queue: Point[] = [point];

    while (queue.length > 0) {
      const p = queue.shift()!;
      const pKey = `${p.x},${p.y}`;

      if (visited.has(pKey)) continue;
      visited.add(pKey);
      contour.points.push(p);

      // Find nearby unvisited edge points
      for (const edge of edges) {
        const eKey = `${edge.x},${edge.y}`;
        if (visited.has(eKey)) continue;

        const dist = Math.sqrt((edge.x - p.x) ** 2 + (edge.y - p.y) ** 2);
        if (dist < 3) {
          queue.push(edge);
        }
      }
    }

    if (contour.points.length > 5) {
      contours.push(contour);
    }
  }

  // Generate G-code for each contour
  for (const contour of contours) {
    if (contour.points.length === 0) continue;

    // Move to start of contour
    const startX = (contour.points[0].x * mmPerPixel).toFixed(3);
    const startY = (contour.points[0].y * mmPerPixel).toFixed(3);
    lines.push(`G0 X${startX} Y${startY}`);
    lines.push(`M3 S${laserPower}`);

    // Trace contour
    for (let i = 1; i < contour.points.length; i++) {
      const x = (contour.points[i].x * mmPerPixel).toFixed(3);
      const y = (contour.points[i].y * mmPerPixel).toFixed(3);
      lines.push(`G1 X${x} Y${y}`);
    }

    // Close contour if needed
    const endX = (contour.points[0].x * mmPerPixel).toFixed(3);
    const endY = (contour.points[0].y * mmPerPixel).toFixed(3);
    lines.push(`G1 X${endX} Y${endY}`);
    lines.push('M5');
  }

  // Footer
  lines.push('');
  lines.push('M5 ; Laser off');
  lines.push('G0 X0 Y0 ; Return to origin');
  lines.push('M2 ; End program');

  return lines.join('\n');
}
